import { Laptop, BookOpen, FileText, ShoppingBag } from "lucide-react"

// Product data
export const productCategories = [
  {
    id: "application",
    title: "Application",
    description: "Powerful digital tools to enhance your project management and learning capabilities",
    icon: <Laptop size={24} />,
    color: "blue",
    products: [
      {
        id: "tumbuh",
        title: "Tumbuh",
        description: "A learning management system specifically designed for coaching and project management.",
        image: "/project-management-suite.png",
        badge: "Popular",
        features: [
          "Customized learning paths",
          "Progress tracking and analytics",
          "Interactive coaching modules",
          "Project management integration",
        ],
        price: "Starting at $49/month",
        link: "/products/tumbuh",
      },
      {
        id: "pantau",
        title: "Pantau",
        description: "A comprehensive project management tool for tracking, managing, and optimizing your projects.",
        image: "/project-dashboard-overview.png",
        features: [
          "Real-time project tracking",
          "Resource allocation",
          "Gantt charts and timelines",
          "Customizable dashboards",
        ],
        price: "Starting at $39/month",
        link: "/products/pantau",
      },
      {
        id: "latih",
        title: "Latih",
        description: "Practice application for certification exam questions with comprehensive feedback and analytics.",
        image: "/project-toolkit.png",
        features: [
          "Thousands of practice questions",
          "Simulated exam environment",
          "Detailed performance analytics",
          "Study plan generator",
        ],
        price: "Starting at $29/month",
        link: "/products/latih",
      },
    ],
  },
  {
    id: "training-kits",
    title: "Training Kits",
    description: "Comprehensive training materials to develop project management skills in your organization",
    icon: <BookOpen size={24} />,
    color: "green",
    products: [
      {
        id: "agile-fundamentals-kit",
        title: "Agile Fundamentals Kit",
        description: "Everything you need to introduce and implement agile methodologies in your organization.",
        image: "/training-session.png",
        badge: "Bestseller",
        features: ["Facilitator guide", "Participant workbooks", "Digital slide deck", "Interactive exercises"],
        price: "$499",
        link: "/products/agile-fundamentals-kit",
      },
      {
        id: "scrum-master-toolkit",
        title: "Scrum Master Toolkit",
        description: "Comprehensive resources for Scrum Masters to effectively facilitate agile teams.",
        image: "/coaching-session.png",
        features: [
          "Scrum ceremony templates",
          "Team health assessment tools",
          "Impediment resolution guides",
          "Retrospective facilitation kit",
        ],
        price: "$349",
        link: "/products/scrum-master-toolkit",
      },
      {
        id: "agile-leadership-program",
        title: "Agile Leadership Program",
        description: "Training program designed to help leaders foster agile mindsets and practices.",
        image: "/consulting-meeting.png",
        features: [
          "Leadership assessment tools",
          "Organizational change guides",
          "Agile governance frameworks",
          "Executive coaching materials",
        ],
        price: "$799",
        link: "/products/agile-leadership-program",
      },
    ],
  },
  {
    id: "templates",
    title: "Templates",
    description: "Ready-to-use templates to streamline your project management processes",
    icon: <FileText size={24} />,
    color: "red",
    products: [
      {
        id: "agile-project-documentation",
        title: "Agile Project Documentation",
        description: "Comprehensive set of templates for documenting agile projects from inception to completion.",
        image: "/project-solutions.png",
        features: [
          "User story templates",
          "Sprint planning documents",
          "Release planning frameworks",
          "Project retrospective guides",
        ],
        price: "$199",
        link: "/products/agile-project-documentation",
      },
      {
        id: "project-management-toolkit",
        title: "Project Management Toolkit",
        description: "Essential templates for traditional project management, compatible with PMI standards.",
        image: "/project-collage.png",
        badge: "Complete",
        features: [
          "Project charter template",
          "WBS and scope documents",
          "Risk register and management plan",
          "Stakeholder communication templates",
        ],
        price: "$249",
        link: "/products/project-management-toolkit",
      },
      {
        id: "agile-metrics-dashboard",
        title: "Agile Metrics Dashboard",
        description: "Ready-to-use dashboards for tracking and visualizing key agile metrics and KPIs.",
        image: "/agile-transformation.png",
        features: ["Velocity tracking", "Burndown/burnup charts", "Cycle time analytics", "Team performance metrics"],
        price: "$149",
        link: "/products/agile-metrics-dashboard",
      },
    ],
  },
  {
    id: "merch",
    title: "Merch & Cards",
    description: "Fun and educational project management merchandise and learning tools",
    icon: <ShoppingBag size={24} />,
    color: "blue",
    products: [
      {
        id: "agile-tshirts",
        title: "Agile T-Shirts",
        description:
          "High-quality t-shirts featuring agile concepts, methodologies, and humorous project management quotes.",
        image: "/vibrant-startup-collaboration.png",
        features: ["Premium cotton material", "Multiple designs available", "Sizes S-XXL", "Bulk discounts for teams"],
        price: "$24.99",
        link: "/products/agile-tshirts",
      },
      {
        id: "project-management-cards",
        title: "Project Management Cards",
        description: "Educational card deck for learning and applying project management concepts and techniques.",
        image: "/collaborative-project-success.png",
        badge: "New",
        features: ["100+ concept cards", "Activity instructions", "Team exercises", "Facilitation guide"],
        price: "$34.99",
        link: "/products/project-management-cards",
      },
      {
        id: "project-management-monopoly",
        title: "Project Management Monopoly",
        description: "Educational board game that simulates project execution with risks, decisions, and trade-offs.",
        image: "/collaborative-healthcare-discussion.png",
        features: ["2-6 players", "60-90 minute gameplay", "Real-world scenarios", "Learning guide included"],
        price: "$59.99",
        link: "/products/project-management-monopoly",
      },
    ],
  },
]
