import { Laptop, BookOpen, FileText, ShoppingBag } from "lucide-react"

// Product data
export const productCategories = [
  {
    id: "application",
    title: "Application",
    description: "Powerful digital tools to enhance your project management and learning capabilities",
    icon: <Laptop size={24} />,
    color: "blue",
    products: [
      {
        id: "tumbuh",
        title: "Tumbuh",
        description: "A learning management system specifically designed for coaching and project management.",
        image:
          "https://images.unsplash.com/photo-1551434678-e076c223a692?w=400&h=300&fit=crop&crop=center&auto=format&q=80",
        badge: "Popular",
        categoryId: "application",
        categoryTitle: "Application",
        categoryColor: "blue",
        features: [
          "Customized learning paths",
          "Progress tracking and analytics",
          "Interactive coaching modules",
          "Project management integration",
        ],
        originalPrice: "Rp 2,499,000",
        price: "Rp 1,999,000",
        link: "/products/tumbuh",
      },
      {
        id: "pantau",
        title: "Pantau",
        description: "A comprehensive project management tool for tracking, managing, and optimizing your projects.",
        image:
          "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop&crop=center&auto=format&q=80",
        categoryId: "application",
        categoryTitle: "Application",
        categoryColor: "blue",
        features: [
          "Real-time project tracking",
          "Resource allocation",
          "Gantt charts and timelines",
          "Customizable dashboards",
        ],
        originalPrice: "Rp 1,999,000",
        price: "Rp 1,599,000",
        link: "/products/pantau",
      },
      {
        id: "latih",
        title: "Latih",
        description: "Practice application for certification exam questions with comprehensive feedback and analytics.",
        image:
          "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=300&fit=crop&crop=center&auto=format&q=80",
        categoryId: "application",
        categoryTitle: "Application",
        categoryColor: "blue",
        features: [
          "Thousands of practice questions",
          "Simulated exam environment",
          "Detailed performance analytics",
          "Study plan generator",
        ],
        price: "Rp 899,000",
        link: "/products/latih",
      },
    ],
  },
  {
    id: "training-kits",
    title: "Training Kits",
    description: "Comprehensive training materials to develop project management skills in your organization",
    icon: <BookOpen size={24} />,
    color: "green",
    products: [
      {
        id: "agile-fundamentals-kit",
        title: "Agile Fundamentals Kit",
        description: "Everything you need to introduce and implement agile methodologies in your organization.",
        image:
          "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop&crop=center&auto=format&q=80",
        badge: "Bestseller",
        categoryId: "training-kits",
        categoryTitle: "Training Kits",
        categoryColor: "green",
        features: ["Facilitator guide", "Participant workbooks", "Digital slide deck", "Interactive exercises"],
        originalPrice: "Rp 1,899,000",
        price: "Rp 1,499,000",
        link: "/products/agile-fundamentals-kit",
      },
      {
        id: "scrum-master-toolkit",
        title: "Scrum Master Toolkit",
        description: "Comprehensive resources for Scrum Masters to effectively facilitate agile teams.",
        image:
          "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=400&h=300&fit=crop&crop=center&auto=format&q=80",
        categoryId: "training-kits",
        categoryTitle: "Training Kits",
        categoryColor: "green",
        features: [
          "Scrum ceremony templates",
          "Team health assessment tools",
          "Impediment resolution guides",
          "Retrospective facilitation kit",
        ],
        originalPrice: "Rp 1,299,000",
        price: "Rp 1,049,000",
        link: "/products/scrum-master-toolkit",
      },
      {
        id: "agile-leadership-program",
        title: "Agile Leadership Program",
        description: "Training program designed to help leaders foster agile mindsets and practices.",
        image:
          "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop&crop=center&auto=format&q=80",
        categoryId: "training-kits",
        categoryTitle: "Training Kits",
        categoryColor: "green",
        features: [
          "Leadership assessment tools",
          "Organizational change guides",
          "Agile governance frameworks",
          "Executive coaching materials",
        ],
        price: "Rp 2,399,000",
        link: "/products/agile-leadership-program",
      },
    ],
  },
  {
    id: "templates",
    title: "Templates",
    description: "Ready-to-use templates to streamline your project management processes",
    icon: <FileText size={24} />,
    color: "red",
    products: [
      {
        id: "agile-project-documentation",
        title: "Agile Project Documentation",
        description: "Comprehensive set of templates for documenting agile projects from inception to completion.",
        image:
          "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=400&h=300&fit=crop&crop=center&auto=format&q=80",
        categoryId: "templates",
        categoryTitle: "Templates",
        categoryColor: "red",
        features: [
          "User story templates",
          "Sprint planning documents",
          "Release planning frameworks",
          "Project retrospective guides",
        ],
        originalPrice: "Rp 799,000",
        price: "Rp 599,000",
        link: "/products/agile-project-documentation",
      },
      {
        id: "project-management-toolkit",
        title: "Project Management Toolkit",
        description: "Essential templates for traditional project management, compatible with PMI standards.",
        image:
          "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=300&fit=crop&crop=center&auto=format&q=80",
        badge: "Complete",
        categoryId: "templates",
        categoryTitle: "Templates",
        categoryColor: "red",
        features: [
          "Project charter template",
          "WBS and scope documents",
          "Risk register and management plan",
          "Stakeholder communication templates",
        ],
        originalPrice: "Rp 999,000",
        price: "Rp 749,000",
        link: "/products/project-management-toolkit",
      },
      {
        id: "agile-metrics-dashboard",
        title: "Agile Metrics Dashboard",
        description: "Ready-to-use dashboards for tracking and visualizing key agile metrics and KPIs.",
        image:
          "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop&crop=center&auto=format&q=80",
        categoryId: "templates",
        categoryTitle: "Templates",
        categoryColor: "red",
        features: ["Velocity tracking", "Burndown/burnup charts", "Cycle time analytics", "Team performance metrics"],
        price: "Rp 449,000",
        link: "/products/agile-metrics-dashboard",
      },
    ],
  },
  {
    id: "merch",
    title: "Merch & Cards",
    description: "Fun and educational project management merchandise and learning tools",
    icon: <ShoppingBag size={24} />,
    color: "blue",
    products: [
      {
        id: "agile-tshirts",
        title: "Agile T-Shirts",
        description:
          "High-quality t-shirts featuring agile concepts, methodologies, and humorous project management quotes.",
        image:
          "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=300&fit=crop&crop=center&auto=format&q=80",
        categoryId: "merch",
        categoryTitle: "Merch & Cards",
        categoryColor: "blue",
        features: ["Premium cotton material", "Multiple designs available", "Sizes S-XXL", "Bulk discounts for teams"],
        originalPrice: "Rp 199,000",
        price: "Rp 149,000",
        link: "/products/agile-tshirts",
      },
      {
        id: "project-management-cards",
        title: "Project Management Cards",
        description: "Educational card deck for learning and applying project management concepts and techniques.",
        image:
          "https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=400&h=300&fit=crop&crop=center&auto=format&q=80",
        badge: "New",
        categoryId: "merch",
        categoryTitle: "Merch & Cards",
        categoryColor: "blue",
        features: ["100+ concept cards", "Activity instructions", "Team exercises", "Facilitation guide"],
        price: "Rp 199,000",
        link: "/products/project-management-cards",
      },
      {
        id: "project-management-monopoly",
        title: "Project Management Monopoly",
        description: "Educational board game that simulates project execution with risks, decisions, and trade-offs.",
        image:
          "https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=400&h=300&fit=crop&crop=center&auto=format&q=80",
        categoryId: "merch",
        categoryTitle: "Merch & Cards",
        categoryColor: "blue",
        features: ["2-6 players", "60-90 minute gameplay", "Real-world scenarios", "Learning guide included"],
        originalPrice: "Rp 449,000",
        price: "Rp 359,000",
        link: "/products/project-management-monopoly",
      },
    ],
  },
]
